[package]
name = "sia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
plotters = "0.3.4"
rand = "0.8.5"
rayon = "1.5"

[dependencies.uuid]
version = "1.2.2"
features = ["v4"]
